name = "DeployToThecloud"
main = "src/index.js"
compatibility_date = "2023-08-01"

# Bindings for Cloudflare services
[[r2_buckets]]
binding = "STORAGE_BUCKET"
bucket_name = "ai-lifeos-storage"

[triggers]
crons = ["0 0 * * *"]  # Daily cleanup

# Environment variables
[vars]
TOGETHER_API_KEY = ""
SENTRY_DSN = ""
